// Mocks generated by Mockito 5.4.4 from annotations
// in budget_tracker/test/features/transactions/presentation/widgets/add_transaction_bottom_sheet_dismissal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i3;

import 'package:budget_tracker/core/error/result.dart' as _i6;
import 'package:budget_tracker/features/accounts/domain/entities/account.dart'
    as _i11;
import 'package:budget_tracker/features/accounts/domain/repositories/account_repository.dart'
    as _i10;
import 'package:budget_tracker/features/transactions/domain/entities/transaction.dart'
    as _i7;
import 'package:budget_tracker/features/transactions/domain/entities/transaction_filter.dart'
    as _i9;
import 'package:budget_tracker/features/transactions/domain/repositories/transaction_category_repository.dart'
    as _i13;
import 'package:budget_tracker/features/transactions/domain/repositories/transaction_repository.dart'
    as _i4;
import 'package:budget_tracker/features/transactions/domain/services/category_icon_color_service.dart'
    as _i12;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIconData_0 extends _i1.SmartFake implements _i2.IconData {
  _FakeIconData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_1 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<_i7.Transaction?>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.Transaction?>>.value(
            _i8.dummyValue<_i6.Result<_i7.Transaction?>>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.Transaction?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getByDateRange,
            [
              start,
              end,
            ],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getByCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [categoryId],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getByCategory,
            [categoryId],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getByType(
          _i7.TransactionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getByType,
            [type],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<_i7.Transaction>> add(_i7.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [transaction],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.Transaction>>.value(
            _i8.dummyValue<_i6.Result<_i7.Transaction>>(
          this,
          Invocation.method(
            #add,
            [transaction],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.Transaction>>);

  @override
  _i5.Future<_i6.Result<_i7.Transaction>> update(
          _i7.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [transaction],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.Transaction>>.value(
            _i8.dummyValue<_i6.Result<_i7.Transaction>>(
          this,
          Invocation.method(
            #update,
            [transaction],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.Transaction>>);

  @override
  _i5.Future<_i6.Result<void>> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue:
            _i5.Future<_i6.Result<void>>.value(_i8.dummyValue<_i6.Result<void>>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<double>> getTotalAmount(
    DateTime? start,
    DateTime? end, {
    _i7.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalAmount,
          [
            start,
            end,
          ],
          {#type: type},
        ),
        returnValue: _i5.Future<_i6.Result<double>>.value(
            _i8.dummyValue<_i6.Result<double>>(
          this,
          Invocation.method(
            #getTotalAmount,
            [
              start,
              end,
            ],
            {#type: type},
          ),
        )),
      ) as _i5.Future<_i6.Result<double>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<int>> getCount() => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
        ),
        returnValue:
            _i5.Future<_i6.Result<int>>.value(_i8.dummyValue<_i6.Result<int>>(
          this,
          Invocation.method(
            #getCount,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getTransactionsPaginated({
    int? limit = 20,
    int? offset = 0,
    _i9.TransactionFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsPaginated,
          [],
          {
            #limit: limit,
            #offset: offset,
            #filter: filter,
          },
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getTransactionsPaginated,
            [],
            {
              #limit: limit,
              #offset: offset,
              #filter: filter,
            },
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>>
      getTransactionsPaginatedByDateRange(
    DateTime? start,
    DateTime? end, {
    int? limit = 20,
    int? offset = 0,
    _i9.TransactionFilter? filter,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTransactionsPaginatedByDateRange,
              [
                start,
                end,
              ],
              {
                #limit: limit,
                #offset: offset,
                #filter: filter,
              },
            ),
            returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
                _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
              this,
              Invocation.method(
                #getTransactionsPaginatedByDateRange,
                [
                  start,
                  end,
                ],
                {
                  #limit: limit,
                  #offset: offset,
                  #filter: filter,
                },
              ),
            )),
          ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getPaginated({
    int? limit = 20,
    int? offset = 0,
    _i9.TransactionFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginated,
          [],
          {
            #limit: limit,
            #offset: offset,
            #filter: filter,
          },
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getPaginated,
            [],
            {
              #limit: limit,
              #offset: offset,
              #filter: filter,
            },
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<int>> getFilteredCount(_i9.TransactionFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilteredCount,
          [filter],
        ),
        returnValue:
            _i5.Future<_i6.Result<int>>.value(_i8.dummyValue<_i6.Result<int>>(
          this,
          Invocation.method(
            #getFilteredCount,
            [filter],
          ),
        )),
      ) as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<List<_i7.Transaction>>> getByAccountId(
          String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByAccountId,
          [accountId],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Transaction>>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Transaction>>>(
          this,
          Invocation.method(
            #getByAccountId,
            [accountId],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Transaction>>>);

  @override
  _i5.Future<_i6.Result<Map<String, double>>> getBalancesByAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalancesByAccount,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<Map<String, double>>>.value(
            _i8.dummyValue<_i6.Result<Map<String, double>>>(
          this,
          Invocation.method(
            #getBalancesByAccount,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<Map<String, double>>>);

  @override
  _i5.Future<_i6.Result<double>> getCalculatedBalance(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalculatedBalance,
          [accountId],
        ),
        returnValue: _i5.Future<_i6.Result<double>>.value(
            _i8.dummyValue<_i6.Result<double>>(
          this,
          Invocation.method(
            #getCalculatedBalance,
            [accountId],
          ),
        )),
      ) as _i5.Future<_i6.Result<double>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i10.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<List<_i11.Account>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i11.Account>>>.value(
            _i8.dummyValue<_i6.Result<List<_i11.Account>>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i11.Account>>>);

  @override
  _i5.Future<_i6.Result<_i11.Account?>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i6.Result<_i11.Account?>>.value(
            _i8.dummyValue<_i6.Result<_i11.Account?>>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i11.Account?>>);

  @override
  _i5.Future<_i6.Result<List<_i11.Account>>> getByType(
          _i11.AccountType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i11.Account>>>.value(
            _i8.dummyValue<_i6.Result<List<_i11.Account>>>(
          this,
          Invocation.method(
            #getByType,
            [type],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i11.Account>>>);

  @override
  _i5.Future<_i6.Result<List<_i11.Account>>> getActive() => (super.noSuchMethod(
        Invocation.method(
          #getActive,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i11.Account>>>.value(
            _i8.dummyValue<_i6.Result<List<_i11.Account>>>(
          this,
          Invocation.method(
            #getActive,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i11.Account>>>);

  @override
  _i5.Future<_i6.Result<_i11.Account>> add(_i11.Account? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [account],
        ),
        returnValue: _i5.Future<_i6.Result<_i11.Account>>.value(
            _i8.dummyValue<_i6.Result<_i11.Account>>(
          this,
          Invocation.method(
            #add,
            [account],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i11.Account>>);

  @override
  _i5.Future<_i6.Result<_i11.Account>> update(_i11.Account? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [account],
        ),
        returnValue: _i5.Future<_i6.Result<_i11.Account>>.value(
            _i8.dummyValue<_i6.Result<_i11.Account>>(
          this,
          Invocation.method(
            #update,
            [account],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i11.Account>>);

  @override
  _i5.Future<_i6.Result<void>> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue:
            _i5.Future<_i6.Result<void>>.value(_i8.dummyValue<_i6.Result<void>>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<double>> getTotalBalance() => (super.noSuchMethod(
        Invocation.method(
          #getTotalBalance,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<double>>.value(
            _i8.dummyValue<_i6.Result<double>>(
          this,
          Invocation.method(
            #getTotalBalance,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<double>>);

  @override
  _i5.Future<_i6.Result<double>> getNetWorth() => (super.noSuchMethod(
        Invocation.method(
          #getNetWorth,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<double>>.value(
            _i8.dummyValue<_i6.Result<double>>(
          this,
          Invocation.method(
            #getNetWorth,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<double>>);

  @override
  _i5.Future<_i6.Result<int>> getCount() => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
        ),
        returnValue:
            _i5.Future<_i6.Result<int>>.value(_i8.dummyValue<_i6.Result<int>>(
          this,
          Invocation.method(
            #getCount,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<List<_i11.Account>>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i11.Account>>>.value(
            _i8.dummyValue<_i6.Result<List<_i11.Account>>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i11.Account>>>);
}

/// A class which mocks [CategoryIconColorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryIconColorService extends _i1.Mock
    implements _i12.CategoryIconColorService {
  MockCategoryIconColorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IconData getIconForCategory(String? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #getIconForCategory,
          [categoryId],
        ),
        returnValue: _FakeIconData_0(
          this,
          Invocation.method(
            #getIconForCategory,
            [categoryId],
          ),
        ),
      ) as _i2.IconData);

  @override
  _i3.Color getColorForCategory(String? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #getColorForCategory,
          [categoryId],
        ),
        returnValue: _FakeColor_1(
          this,
          Invocation.method(
            #getColorForCategory,
            [categoryId],
          ),
        ),
      ) as _i3.Color);

  @override
  ({_i3.Color color, _i2.IconData icon}) getIconAndColorForCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIconAndColorForCategory,
          [categoryId],
        ),
        returnValue: (
          color: _FakeColor_1(
            this,
            Invocation.method(
              #getIconAndColorForCategory,
              [categoryId],
            ),
          ),
          icon: _FakeIconData_0(
            this,
            Invocation.method(
              #getIconAndColorForCategory,
              [categoryId],
            ),
          )
        ),
      ) as ({_i3.Color color, _i2.IconData icon}));
}

/// A class which mocks [TransactionCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionCategoryRepository extends _i1.Mock
    implements _i13.TransactionCategoryRepository {
  MockTransactionCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionCategory>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i5.Future<_i6.Result<List<_i7.TransactionCategory>>>.value(
                _i8.dummyValue<_i6.Result<List<_i7.TransactionCategory>>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.TransactionCategory>>>);

  @override
  _i5.Future<_i6.Result<_i7.TransactionCategory?>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.TransactionCategory?>>.value(
            _i8.dummyValue<_i6.Result<_i7.TransactionCategory?>>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.TransactionCategory?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionCategory>>> getByType(
          _i7.TransactionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue:
            _i5.Future<_i6.Result<List<_i7.TransactionCategory>>>.value(
                _i8.dummyValue<_i6.Result<List<_i7.TransactionCategory>>>(
          this,
          Invocation.method(
            #getByType,
            [type],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.TransactionCategory>>>);

  @override
  _i5.Future<_i6.Result<_i7.TransactionCategory>> add(
          _i7.TransactionCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [category],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.TransactionCategory>>.value(
            _i8.dummyValue<_i6.Result<_i7.TransactionCategory>>(
          this,
          Invocation.method(
            #add,
            [category],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.TransactionCategory>>);

  @override
  _i5.Future<_i6.Result<_i7.TransactionCategory>> update(
          _i7.TransactionCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [category],
        ),
        returnValue: _i5.Future<_i6.Result<_i7.TransactionCategory>>.value(
            _i8.dummyValue<_i6.Result<_i7.TransactionCategory>>(
          this,
          Invocation.method(
            #update,
            [category],
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.TransactionCategory>>);

  @override
  _i5.Future<_i6.Result<void>> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue:
            _i5.Future<_i6.Result<void>>.value(_i8.dummyValue<_i6.Result<void>>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<bool>> isCategoryInUse(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCategoryInUse,
          [categoryId],
        ),
        returnValue:
            _i5.Future<_i6.Result<bool>>.value(_i8.dummyValue<_i6.Result<bool>>(
          this,
          Invocation.method(
            #isCategoryInUse,
            [categoryId],
          ),
        )),
      ) as _i5.Future<_i6.Result<bool>>);
}
