// Mocks generated by Mockito 5.4.4 from annotations
// in budget_tracker/test/features/settings/presentation/screens/settings_screen_enhanced_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:budget_tracker/features/settings/domain/entities/settings.dart'
    as _i7;
import 'package:budget_tracker/features/settings/presentation/notifiers/settings_notifier.dart'
    as _i3;
import 'package:budget_tracker/features/settings/presentation/states/settings_state.dart'
    as _i5;
import 'package:flutter/material.dart' as _i6;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsNotifier extends _i1.Mock implements _i3.SettingsNotifier {
  MockSettingsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i2.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.AsyncValue<_i5.SettingsState>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.AsyncValue<_i5.SettingsState>>.empty(),
      ) as _i4.Stream<_i2.AsyncValue<_i5.SettingsState>>);

  @override
  _i2.AsyncValue<_i5.SettingsState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_0<_i5.SettingsState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<_i5.SettingsState>);

  @override
  set state(_i2.AsyncValue<_i5.SettingsState>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AsyncValue<_i5.SettingsState> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAsyncValue_0<_i5.SettingsState>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.AsyncValue<_i5.SettingsState>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadSettings() => (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> updateThemeMode(_i6.ThemeMode? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThemeMode,
          [themeMode],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateCurrencyCode(String? currencyCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCurrencyCode,
          [currencyCode],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateBudgetAlertsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBudgetAlertsEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateBillRemindersEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBillRemindersEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateBudgetAlertThreshold(int? threshold) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBudgetAlertThreshold,
          [threshold],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateBillReminderDays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #updateBillReminderDays,
          [days],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateIncomeRemindersEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIncomeRemindersEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateIncomeReminderDays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #updateIncomeReminderDays,
          [days],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> exportData(_i7.DataExportType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportData,
          [type],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> updateSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i5.SettingsState>? old,
    _i2.AsyncValue<_i5.SettingsState>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.RemoveListener addListener(
    _i8.Listener<_i2.AsyncValue<_i5.SettingsState>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
